
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "Atom BinOp UnaOpForm : AtomForm : '(' Form ')'Form : UnaOp FormForm : Form BinOp Form"
    
_lr_action_items = {'Atom':([0,3,4,5,],[2,2,2,2,]),'(':([0,3,4,5,],[3,3,3,3,]),'UnaOp':([0,3,4,5,],[4,4,4,4,]),'$end':([1,2,7,8,9,],[0,-1,-3,-4,-2,]),'BinOp':([1,2,6,7,8,9,],[5,-1,5,5,5,-2,]),')':([2,6,7,8,9,],[-1,9,-3,-4,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Form':([0,3,4,5,],[1,6,7,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Form","S'",1,None,None,None),
  ('Form -> Atom','Form',1,'p_form_atom','parser.py',10),
  ('Form -> ( Form )','Form',3,'p_form_paren','parser.py',14),
  ('Form -> UnaOp Form','Form',2,'p_form_una','parser.py',18),
  ('Form -> Form BinOp Form','Form',3,'p_form_bin','parser.py',22),
]
